name: pocket-js-server
#Mudar para USER caso o environment esteja errado
services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit